name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
    - uses: TimWillebrands/setup-c3@v2

    - name: Build project
      run: c3c -O2 -g0 build fib_c3

    - name: Run tests
      run: c3c test
